#########
# General
#########

# Renumber windows dynamically
set-option -g renumber-windows on

# Be quiet
set-option -g bell-action none
set-option -g visual-activity off
set-option -g visual-bell off
set-option -g visual-silence off
set-option -g monitor-activity off

# Don't rename windows automatically
set-option -g allow-rename off

# Use Vim bindings for copy & selection
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi r send-keys -X rectangle-toggle

# Copy to system clipboard
set-option -g set-clipboard on
set-option -g allow-passthrough on

# Stay in copy mode after mouse selection
unbind-key -T copy-mode-vi MouseDragEnd1Pane

# Prompt to rename window right after it's created
set-hook -g after-new-window 'command-prompt -I "#{window_name}" "rename-window '%%'"'

#########
# Hotkeys
#########

# Note: '-r' option allows "repeating" commands,
# so you don't have to hit the prefix each time

# Remap prefix from 'C-b' to 'C-a'
unbind-key C-b
set-option -g prefix C-a
bind-key -N "Send raw prefix" \
    C-a send-prefix

# Reload config
bind-key -N "Re-source config" \
    S source-file "~/.config/tmux/tmux.conf" \; display-message "tmux.conf reloaded."

# Select panes with vim motions
bind-key -N "Move pane focus up" -r \
    C-k  select-pane -U
bind-key -N "Move pane focus down" -r \
    C-j  select-pane -D
bind-key -N "Move pane focus left" -r \
    C-h  select-pane -L
bind-key -N "Move pane focus right" -r \
    C-l  select-pane -R

# Window controls
bind-key -N "Select previous window" -r \
    C-[ previous-window
bind-key -N "Select next window" -r \
    C-] next-window
bind-key -N "Rotate current window" -r \
    C-o rotate-window
bind-key -N "Select last window" -r \
    C-\\ last-window

# Rename window/session
bind-key -N "Rename current window" \
    r command-prompt -I "#{window_name}" "rename-window '%%'"
bind-key -N "Rename current session" \
    R command-prompt -I "#{session_name}" "rename-session '%%'"

# Create splits
bind-key -N "Split window horizontal" \
    | split-window -h
bind-key -N "Split window veritically" \
    _ split-window -v

# New windows retain cwd
bind-key -N "Create new window" \
    c new-window -c "#{pane_current_path}"

# Remap zoom from 'C-z' to 'C-x'
unbind-key C-z
bind-key C-x resize-pane -Z

# Paste from TMUX buffer
bind-key -N "Paste" \
    P paste-buffer

# List TMUX hotkeys
bind-key -N "List keys" \
    ? list-keys -Na

#########
# Status
#########

# See https://man.openbsd.org/tmux.1#FORMATS for format options.

# Enable status line
set-option -g status on
set-option -g status-right ' #{?client_prefix,#[reverse]<Prefix>#[noreverse] ,}[%H:%M %d-%b-%y]'
#set-option -g status-right '#{?window_bigger,[#{window_offset_x}#,#{window_offset_y}] ,}"#{=21:pane_title}" %H:%M %d-%b-%y'

