[wallpapers]

[wallpapers.fog_forest]
file = "wallpapers/fog_forest.webp"
description = "Foggy forest landscape"
source = "https://imgur.com/kGhIyoh"
width = 1920
height = 1080
aspect_ratio = "16:9"
color_scheme = "dark"
dominant_color = "#7b736f"
palette = ["#beada3", "#8a7f78", "#6b6662", "#5a5856", "#414344"]

[wallpapers.girl_adjusting_glasses]
file = "wallpapers/girl_adjusting_glasses.png"
description = "Girl adjusting glasses"
source = "https://www.pixiv.net/en/users/96yottea"
width = 5120
height = 2880
aspect_ratio = "16:9"
color_scheme = "dark"
dominant_color = "#5e272e"
palette = ["#89648d", "#5f3b4c", "#98211d", "#491514", "#070b0b"]

[wallpapers.girl_leaving_apartment]
file = "wallpapers/girl_leaving_apartment.png"
description = "Girl leaving apartment"
source = "https://wallhaven.cc/w/zy1xjw"
width = 1920
height = 1080
aspect_ratio = "16:9"
color_scheme = "dark"
dominant_color = "#436379"
palette = ["#809fb6", "#5081a5", "#497392", "#3a5b72", "#19272f"]

[wallpapers.girls_outside_door]
file = "wallpapers/girls_outside_door.jpg"
description = "Girls outside door"
source = "https://x.com/nemuiZZZxN"
width = 3664
height = 2059
aspect_ratio = "16:9"
color_scheme = "dark"
dominant_color = "#41473e"
palette = ["#82a68f", "#59695c", "#4e4b41", "#332d28", "#121413"]

[wallpapers.pixel_city_art]
file = "wallpapers/pixel_city_art.gif"
description = "Pixel city art"
source = "https://www.pixiv.net/en/users/waneella"
width = 1500
height = 900
aspect_ratio = "5:3"
color_scheme = "dark"
dominant_color = "#152127"
palette = ["#505d7b", "#3b3847", "#0b222a", "#03120d", "#000301"]

[icons]

[icons.baozi]
theme = "hicolor"
context = "apps"
file = "icons/hicolor/{dimension}/apps/baozi.png"
dimensions = ["16x16", "22x22", "24x24", "32x32", "48x48", "64x64", "128x128", "256x256", "512x512"]
description = "Baozi mascot / avatar"
source = "local/baozi"
color_scheme = "light"
dominant_color = "#a88f6f"
palette = ["#f6f0dd", "#ebd6b6", "#bfa985", "#9a7447", "#523720"]
